### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GarronFish** [NTNU-IHB/FMI4cpp#101]
When running running conan to install FMI4cpp/testing on Windows I get the following error:
ERROR: Conflict in libzip/1.5.2@bincrafters/stable:
    'libzip/1.5.2@bincrafters/stable' requires 'zlib/1.2.11' while 'boost/1.66.0@conan/stable' requires 'zlib/1.2.11@conan/stable'.

This was done in FMI4cpp-conan-master by running a conan console and then running **conan create . FMI4cpp/testing**

**Comment by markaren** [comment]
I'll have a look today. The conan repo might be a little out of date.

**Comment by markaren** [comment]
FMI4cpp-conan should be fixed now. Targets 0.8.0-ALPHA, which I just made a release of.

**Comment by GarronFish** [comment]
Thanks,

Now I get:
ERROR: Failed requirement 'openssl/1.0.2u' from 'libzip/1.5.2@bincrafters/stable'
ERROR: Requested 'openssl/1.0.2u' but found case incompatible 'OpenSSL'
Case insensitive filesystem can't manage this

**Comment by markaren** [comment]
That one is related to Conan itself. You need to clear the conan cache and re-run.

**Comment by GarronFish** [comment]
Cleared cache by changing environmental variable CONAN_USER_HOME
Now get:
ERROR: Missing binary: boost/1.66.0@conan/stable:e6323f6266863b5b9bc7a29b1cde8113bdde591f

Thanks for the help

**Comment by GarronFish** [comment]
I tried this:
conan create . FMI4cpp/testing --build=boost --build=fmi4cpp
and then got this error:
ERROR: boost/1.66.0@conan/stable: Error in build() method, line 89
        b2_exe = self.bootstrap()
while calling 'bootstrap', line 293
        self.run(cmd)
        ConanException: Error 1 while executing bootstrap.bat vc16

**Comment by markaren** [comment]
I'm not so sure changing home dir was the best solution. Just delete the cache folder. This is an issue common to all conan recepies as some libraries changed their name.
It should not be necessary to build boost manually.

**Comment by GarronFish** [comment]
I'm still getting this:

Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.66.0@conan/stable:e6323f6266863b5b9bc7a29b1cde8113bdde591f

boost/1.66.0@conan/stable: WARN: Can't find a 'boost/1.66.0@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=16, os=Windows
- Options: header_only=False, shared=True, skip_lib_rename=False, without_atomic=False, without_chrono=False, without_container=False, without_context=False, without_coroutine=False, without_date_time=False, without_exception=False, without_fiber=False, without_filesystem=False, without_graph=False, without_graph_parallel=False, without_iostreams=False, without_locale=False, without_log=False, without_math=False, without_mpi=False, without_program_options=False, without_python=True, without_random=False, without_regex=False, without_serialization=False, without_signals=False, without_stacktrace=False, without_system=False, without_test=False, without_thread=False, without_timer=False, without_type_erasure=False, without_wave=False, bzip2:build_executable=True, bzip2:shared=False, zlib:minizip=False, zlib:shared=False
- Dependencies: bzip2/1.0.8, zlib/1.2.11
- Requirements: bzip2/1.Y.Z, zlib/1.Y.Z
- Package ID: e6323f6266863b5b9bc7a29b1cde8113bdde591f

ERROR: Missing prebuilt package for 'boost/1.66.0@conan/stable'
Try to build from sources with '--build=boost'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'

**Comment by markaren** [comment]
Are you using VS 2019? As far as I can remember, there are no pre-built boost (for this version) for that version of VS. So, yes, you'd need to tell conan to build it. Another solution would be to upgrade the conan dependency. I have not done that, becouse they changed where artifacts are stored in later versions, so I can't just bump the verrsion.

**Comment by markaren** [comment]
I'll have a go at upgrading boost.

**Comment by markaren** [comment]
Try now

**Comment by GarronFish** [comment]
I tried again.  First I cleared out the cache again then opened a cmd console, cd to FMI4cpp-conan-master and then ran:

C:\Users\Garron\Desktop\FMI4cpp-conan-master>conan create . FMI4cpp/testing

It still appears to be looking for boost 1.66 for some reason.  Am I doing something wrong?

Here is the full error message:

`WARN: Remotes registry file missing, creating default one in C:\Users\Garron\.conan\remotes.json
Auto detecting your dev setup to initialize the default profile (C:\Users\Garron\.conan\profiles\default)
Found Visual Studio 16
Default settings
        os=Windows
        os_build=Windows
        arch=x86_64
        arch_build=x86_64
        compiler=Visual Studio
        compiler.version=16
        build_type=Release
*** You can change them in C:\Users\Garron\.conan\profiles\default ***
*** Or override with -s compiler='other' -s ...s***


Exporting package recipe
fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing: A new conanfile.py version was exported
fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing: Folder: C:\Users\Garron\.conan\data\fmi4cpp\0.8.0-ALPHA\FMI4cpp\testing\export
fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing: Exported revision: ec12dc80251dcbe283fd6d5feb657d9a
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

boost/1.66.0@conan/stable: Not found in local cache, looking in remotes...
boost/1.66.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.06k]
Downloading conanfile.py completed [17.31k]
boost/1.66.0@conan/stable: Downloaded recipe revision 0
WARN: boost/1.66.0@conan/stable: requirement bzip2/1.0.6@conan/stable overridden by fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing to bzip2/1.0.8
WARN: boost/1.66.0@conan/stable: requirement zlib/1.2.11@conan/stable overridden by fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing to zlib/1.2.11
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [2.07k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
bzip2/1.0.8: Downloaded recipe revision 0
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.40k]
Downloading conanfile.py completed [8.35k]
Downloading conan_export.tgz completed [0.33k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.11: Downloaded recipe revision 0
libzip/1.5.2@bincrafters/stable: Not found in local cache, looking in remotes...
libzip/1.5.2@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.24k]
Downloading conanfile.py completed [3.20k]
Downloading conan_export.tgz completed [0.29k]
Decompressing conan_export.tgz completed [0.00k]
libzip/1.5.2@bincrafters/stable: Downloaded recipe revision 0
openssl/1.0.2u: Not found in local cache, looking in remotes...
openssl/1.0.2u: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [33.84k]
Downloading conan_export.tgz completed [0.25k]
Decompressing conan_export.tgz completed [0.00k]
openssl/1.0.2u: Downloaded recipe revision 0
fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing: Forced build from source
fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing (test package): Installing package
Requirements
    boost/1.66.0@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.8 from 'conan-center' - Downloaded
    fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing from local cache - Cache
    libzip/1.5.2@bincrafters/stable from 'conan-center' - Downloaded
    openssl/1.0.2u from 'conan-center' - Downloaded
    zlib/1.2.11 from 'conan-center' - Downloaded
Packages
    boost/1.66.0@conan/stable:e6323f6266863b5b9bc7a29b1cde8113bdde591f - Missing
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Download
    fmi4cpp/0.8.0-ALPHA@FMI4cpp/testing:f02e2b8f7409fb01c4f812af6530d9c78a251833 - Build
    libzip/1.5.2@bincrafters/stable:82ec74caf07463d4bb021d356cad05d827340c71 - Download
    openssl/1.0.2u:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Download
    zlib/1.2.11:3fb49604f9c2f729b85ba3115852006824e72cab - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: boost/1.66.0@conan/stable:e6323f6266863b5b9bc7a29b1cde8113bdde591f

boost/1.66.0@conan/stable: WARN: Can't find a 'boost/1.66.0@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=16, os=Windows
- Options: header_only=False, shared=True, skip_lib_rename=False, without_atomic=False, without_chrono=False, without_container=False, without_context=False, without_coroutine=False, without_date_time=False, without_exception=False, without_fiber=False, without_filesystem=False, without_graph=False, without_graph_parallel=False, without_iostreams=False, without_locale=False, without_log=False, without_math=False, without_mpi=False, without_program_options=False, without_python=True, without_random=False, without_regex=False, without_serialization=False, without_signals=False, without_stacktrace=False, without_system=False, without_test=False, without_thread=False, without_timer=False, without_type_erasure=False, without_wave=False, bzip2:build_executable=True, bzip2:shared=False, zlib:minizip=False, zlib:shared=False
- Dependencies: bzip2/1.0.8, zlib/1.2.11
- Requirements: bzip2/1.Y.Z, zlib/1.Y.Z
- Package ID: e6323f6266863b5b9bc7a29b1cde8113bdde591f

ERROR: Missing prebuilt package for 'boost/1.66.0@conan/stable'

Try to build from sources with '--build=boost'
Use 'conan search <reference> --table table.html'
Or read 'http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'`

**Comment by GarronFish** [comment]
Its all working!  Thanks I owe you some beers!
I tested **example** and this appears to work as expected.
