### ISSUE TITLE
Could not load dynamic libary

### ISSUE THREAD

**Issue by FuBuman** [NTNU-IHB/FMI4cpp#105]
if im loading my FMU, i get this Error:

\v0.7.0-85bef849b4.clean\src\fmi2\fmi2_library.cpp:91: Unable to load dynamic library '-------"......\fmi4cpp_MFLEX_Blocks_FMU_RobotPlattformControlled_52703516/binaries/win32/MFLEX_Blocks_FMU_RobotPlattformControlled.dll'! 126

**Comment by markaren** [comment]
I can only speculate on the cause. Does it work in other tools?

**Comment by FuBuman** [comment]
i just tried it out in Visual studio, my fmu does not support Modelexchange, has it any impacts cause of that?

**Comment by markaren** [comment]
I doubt it. The error occurs during Windows `LoadLibrary`, so I'm guessing you will get the same error in other tools. So this is probably not a fmi4cpp issue. That's why I asked if it works in other tools, fmilib, fmpy etc. It might be caused by missing dlls on your system, but I can only speculate.

**Comment by FuBuman** [comment]
i treid it out today with fmPy, it works there

**Comment by markaren** [comment]
Then I guess it is a bitness issue. VS is default 32 bit no? FMPy probably ran it in 64 bit mode.

**Comment by FuBuman** [comment]
so... i tried it out, its seems to be a 32/64 bit problem ;) maybe you should write only a 32 bit support in the readme. next person will thank you ;)

**Comment by markaren** [comment]
> maybe you should write only a 32 bit support in the readme. next person will thank you

Well, it's a FMU issue not a fmi4cpp issue.
