### ISSUE TITLE
encounter some syntax error in my project

### ISSUE THREAD

**Issue by mycrocs** [NTNU-IHB/FMI4cpp#124]
Hi,
When i use fmi4cpp in my project, it encounter some syntax error. 
![image](https://user-images.githubusercontent.com/31428244/150248162-53f3272e-618b-4958-b2ba-027b3f4f1553.png)

These errors are in the code below, but i cannot see anything wrong.
![image](https://user-images.githubusercontent.com/31428244/150248311-e26203e9-fae6-41f9-a625-256214f51365.png)

I am using VS2017 and set language standard C++17.
I install the library from vcpkg.

**Comment by markaren** [comment]
> I install the library from vcpkg.

Oh, that version is wildly outdated and quite different from what you see when browsing the code on github.

I suspect the issue is a missing NO_MIN_MAX define, though. But using the vcpkg version is ill advised. It will not be updated and is years old.

**Comment by mycrocs** [comment]
Thanks, i will try.

**Comment by markaren** [comment]
Someone has actually updated the vcpkg port lately. Then it isn't as outdated as I thought. 
Your issue is still probably with NO_MIN_MAX, though.
