### ISSUE TITLE
How to simulate a model_exchange model?

### ISSUE THREAD

**Issue by mycrocs** [NTNU-IHB/FMI4cpp#126]
Should i wrap the me model to cs model first If i want to simulate a model_exchange model?

**Comment by markaren** [comment]
FMI4cpp provides the ME interface functions as per the standard. How you go about using that interface is up to you.
Older versions had support for doing this, but I can't vouch for it's validity so it was removed.

**Comment by mycrocs** [comment]
Do you mean i need to assign the solver first and do something to run it like the older version did?
I am new in this area. Are there any examples i can refer if i need to do so?
Thanks.
