### ISSUE TITLE
Can not open file "fmi4cpp::fmi4cpp.lib"?

### ISSUE THREAD

**Issue by firefall123** [NTNU-IHB/FMI4cpp#134]
I open the D:\Git\FMI4cpp\examples and build this project. There is the question. can not open file "fmi4cpp::fmi4cpp.lib". I don't know what I did wrong. Where is the fmi4cpp::fmi4cpp.lib

**Comment by markaren** [comment]
I don't know. Are you using a wildly obsolete CMake version?
How do you build the project?

**Comment by firefall123** [comment]
> I don't know. Are you using a wildly obsolete CMake version? How do you build the project?



> Just cmake the CMakeLists.txt. in examples. Not a  obsolete CMake version. Maybe the build process went wrong

**Comment by markaren** [comment]
Closing as user having CMake issues, not related to this library.
