### ISSUE TITLE
abuot the fmi4cpp::fmi4cpp.lib

### ISSUE THREAD

**Issue by firefall123** [NTNU-IHB/FMI4cpp#135]
hello, Why is there fmi4cpp:: fmi4cpp.lib in the attached dependency, but there is no such lib in the project
fmi4cpp::fmi4cpp.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib

**Comment by markaren** [comment]
It is not clear what issue you are having. How are you building and linking the project?

**Comment by firefall123** [comment]
I just started to learn FMU. Could you please tell me how to build the project with vs2017 under Windows environment

**Comment by markaren** [comment]
It's a regular CMake project. See e.g. https://github.com/NTNU-IHB/FMI4cpp/blob/master/.github/workflows/config.yml

**Comment by firefall123** [comment]
I realized that I had not studied Conan in the past. Thank you. I'll try again.

**Comment by firefall123** [comment]
I succeeded. Thank you so much for your help.
