### ISSUE TITLE
Unable to compile fmi4cpp with mingw

### ISSUE THREAD

**Issue by netpay2007** [NTNU-IHB/FMI4cpp#140]
Hi, i am trying to compile fmi4cpp with mingw in windows, but it signals many errors:
![image](https://user-images.githubusercontent.com/131646014/233921413-4a1882dc-313b-464a-9214-628099c1df7c.png)
fmi4cpp is a very valuable lib, and is it not support mingw?

**Comment by netpay2007** [comment]
i know ,it is a bug in mingw810

**Comment by markaren** [comment]
I was going to comment that you likely need a newer mingw (gcc) version, but I have never tested on mingw. However, I don't see why it would not work.

**Comment by netpay2007** [comment]
i use the mingw810 to compile the fmi4cpp, but it trigger a bug in mingw810 , and signals many errors.
![2e19008bf97b2b2625d955f4882c619](https://user-images.githubusercontent.com/131646014/233939764-1d18d516-2fb0-4a6d-9aeb-cfcceded050b.png)
