### ISSUE TITLE
unable to compile the fmi4cpp

### ISSUE THREAD

**Issue by netpay2007** [NTNU-IHB/FMI4cpp#141]
hi, i am trying to compile the fmi4cpp, but it signal a error: fatal error: pugixml.hpp: No such file or directory. In fact, i have include the dir of the pugixml.hpp, is there any wrong in the setting? 
![image](https://user-images.githubusercontent.com/131646014/234523083-6e3fce24-9a4c-40cd-98dd-a8e208c0f2e8.png)
![image](https://user-images.githubusercontent.com/131646014/234523346-93d9da3d-1261-4b42-bc65-9ea9f7cddb45.png)
![image](https://user-images.githubusercontent.com/131646014/234523456-5598c97e-c52f-44b2-879b-58c18c56a318.png)

**Comment by netpay2007** [comment]
![image](https://user-images.githubusercontent.com/131646014/234524350-813f6bb7-3caa-4dd4-a669-866cd32023e8.png)

**Comment by markaren** [comment]
I dunno, but I'd consider using conan 1.x or vcpkg: https://github.com/NTNU-IHB/FMI4cpp/pull/139 for handlig depedencies on windows.

**Comment by netpay2007** [comment]
OK,thinks, i will have a try
