### ISSUE TITLE
Response from remote is not json

### ISSUE THREAD

**Issue by Number-One-Intern** [NTNU-IHB/FMI4cpp#143]
Hi, I'm currently trying to build FMI4cpp with conan. But whenever I attempt to I get this error in the terminal:

"Response from remote is not json, but 'text/html; charset=utf-8'. [Remote: ais]"

And based off installation.md I do not have the wrong url.

"conan remote list
ais: https://ais.jfrog.io/artifactory/api/conan/ais-conan-local [Verify SSL: False]
conancenter: https://center.conan.io [Verify SSL: False]"

For reference I'm currently trying to use conan 1.6, and operating through a container in WSL.

**Comment by markaren** [comment]
Hi, try https://github.com/NTNU-IHB/FMI4cpp/pull/139

**Comment by Number-One-Intern** [comment]
I was able to clone #139 run, "sudo apt-get install libzip-dev libpugixml-dev", and then able to configure and build. I have one last question though. I am quite familiar with FMPy, but this is my first time interacting with FMI4cpp are there any special steps I have to take to run the examples?

**Comment by markaren** [comment]
You need to pass '-DFMI4CPP_BUILD_EXAMPLES=ON' if you have not already.

**Comment by Number-One-Intern** [comment]
Ok, thank you for your help it has been very useful. I ran that command to cmake and got no errors as well as  

'-DFMI4CPP_BUILD_TESTS=ON.'

But this is my actual last question. I am trying to run fmu_test.cpp. But is there something else I am missing to run it? Because I tried using run and debug with a c++ compiler and ended up with an include error for, 

'#include <fmi4cpp/fmi4cpp.hpp>'

Which I assume shouldn't be an issue since everything built correctly.

**Comment by markaren** [comment]
It might be that you are trying to run a `.cpp` file and not an actual CMake target. Check if there are executables in your build folder that you can invoke from the termnial. If they work you are good. And since you built the code, it should be ok.

**Comment by Number-One-Intern** [comment]
![image](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/e654e3c3-6429-4ecb-996a-6e6744944b99)
There doesn't seem to be any executables in the build folder despite having no build issues.

**Comment by markaren** [comment]
Check the out or examples folder.

**Comment by Number-One-Intern** [comment]
![Screenshot 2024-06-28 120211](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/3c99b03e-cfcd-4ef4-ab2d-ad13f4de2378)
![Screenshot 2024-06-28 120335](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/a3ae0e68-8a5c-402f-a7e0-70471f2ab332)
I was still unable to find any.

**Comment by markaren** [comment]
Check the .dir files or observe the output feom CMake to find the location. Anyhow, note that this has to do with how CMake is invoked, not fmi4cpp by itself.

**Comment by Number-One-Intern** [comment]
These are my terminal outputs.
![image](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/1a98b8a5-e72b-4c53-9c57-bbc182c8017a)
![Screenshot 2024-06-28 121335](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/f6119bdd-0ec8-444b-b286-fe4ab1ca1a6b)
![Screenshot 2024-06-28 121346](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/6f0858c1-141b-4d39-b85a-106f1d2a66d5)
They the files are being written to FMI4cpp itself but I do not see them in the directory. The same  for out/build/configure. This is also what one of the insides of the .dir files looks like.
![image](https://github.com/NTNU-IHB/FMI4cpp/assets/171373702/84a5eb86-6f04-4212-9b92-3ae3282d367c)

**Comment by markaren** [comment]
Check the CI workflow for how CMake ought to be invoked.

**Comment by Number-One-Intern** [comment]
Sorry, I am unsure what the CI workflow is. But I edited the comment to include the build terminal image as well. Unless I have mistaken that output for the build step completing.

**Comment by markaren** [comment]
https://github.com/NTNU-IHB/FMI4cpp/blob/vcpkg/.github/workflows/config.yml

**Comment by Number-One-Intern** [comment]
Thank for you help I was able to run the tests with no problems and run the test_fmu.
