### ISSUE TITLE
Memory leak when unable to terminate FMU

### ISSUE THREAD

**Issue by stephen-ryan-ansys** [NTNU-IHB/FMI4cpp#146]
When using the library, I am encountering a memory leak in the situation where the program exits when the FMU is not in a state where terminate is allowed to be called. For example, if an exception is thrown after `enter_initialization_mode()` is called, but before `exit_initialization_mode()` is called. I looked at the destructor in the `fmu_instance_base` class, and it is calling `terminate()`, which attempts to terminate the FMU and free the resources:

```cpp
    bool terminate(bool freeInstance)
    {
        if (!this->terminated_) {
            this->terminated_ = true;
            if (!library_->terminate(c_)) {
                return false;
            }
            this->free_instance();
        }
        return true;
    }
```

However, if the library fails to terminate the FMU, the function returns early with `false`, and the `free_instance()` function is never called. This corresponds to `fmi2FreeInstance`, which should be callable even when the FMU is not terminated. It could be changed to something like the following.

```cpp
    bool terminate(bool freeInstance)
    {
        if (!this->terminated_) {
            this->terminated_ = library_->terminate(c_);
        }
        this->free_instance();
        return this->terminated_;
    }
```

Or the call to `free_instance` can be removed from `terminate` and simply called from the destructor like:

```cpp
    ~fmu_instance_base()
    {
        terminate();
        free_instance();
    }
```

**Comment by markaren** [comment]
I'll see if I can look into this not to long into the future. I notice that `bool freeInstance` is not actually used, so the code path needs some cleanup regardless.
