### ISSUE TITLE
Make it possible to simulate system of slaves

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/FMI4cpp#24]
With pluggable master algorithms and possible support for [SSP](https://github.com/modelica/ssp-standard.org).

Distributed execution would be available using [FMU-proxy](https://github.com/SFI-Mechatronics/FMU-proxy), as FMU proxy clients implements FMI4cpp's [FmuSlave](https://github.com/SFI-Mechatronics/FMI4cpp/blob/e9dca0db9a33eb22d172e62f306cc3ae7d40185c/include/fmi4cpp/fmi2/import/FmuSlave.hpp).

See https://github.com/SFI-Mechatronics/FMI4j/issues/44

**Comment by traversaro** [comment]
A first draft of the SSP standard is now available at: https://ssp-standard.org/publications/SSP10RC1/SystemStructureAndParameterization10RC1.pdf .

**Comment by markaren** [comment]
Closing as I don't see this happening in the scope of fmi4cpp.
