### ISSUE TITLE
FmuResource::getResourcePath() returns wrong path?

### ISSUE THREAD

**Issue by kepakiano** [NTNU-IHB/FMI4cpp#60]
When using the current master of `omc` to generate an FMU, the file `<model>_info.json` is put directly into the `resources` folder inside the FMU. However, FMI4cpp looks for it in the folder `"resources" + getOs() + "/" + getLibExt()`, which for me is `resources/linux64/.so` and thus cannot find the file.
Is this a bug? When I remove adding `getOs()` and `getLibExt()` everything works as expected.

**Comment by markaren** [comment]
Yes, this is a bug I discovered recently. It was fixed 4 days ago.

https://github.com/NTNU-IHB/FMI4cpp/blob/master/src/fmu_resource.cpp

**Comment by markaren** [comment]
Which version of FMI4cpp are you using btw, and how are you getting it?
This fix will be in 0.7.0 which will be a pretty major release as far as breaking changes are concerned.

**Comment by markaren** [comment]
Closing since this fix is present on the master branch
