### ISSUE TITLE
How can i use fmi4cpp in VS2013

### ISSUE THREAD

**Issue by fresh-ji** [NTNU-IHB/FMI4cpp#96]
Thanks for your generous replying!

**Comment by markaren** [comment]
I've never used VS myself, so I can't offer a very specific answer.
I guess you have some options:
* Build fmi4cpp from commandline (see .github/workflows for example) and include/link manually.
* Recommended. Use fmi4cpp as a CMake submodule (Assuming you can do that in VS)
* Use conan (https://github.com/markaren/FMI4cpp-conan). However I see that this receipt out of date.

There is also an old __unmaintained__ version available on vcpkg.
