### ISSUE TITLE
Adding C headers

### ISSUE THREAD

**Issue by andre2007** [NTNU-IHB/FMI4cpp#98]
It would be great if you could provide C headers also, to access the library FMI4cpp. I would like to call this library from the D Programming Language. D can easily access libraries which has a C headers (and to a specific degree also C++ headers, but here I failed).

**Comment by markaren** [comment]
I won't be providing C headers for this library. I suggest you use FMI Library, which is written in C.

**Comment by andre2007** [comment]
Thanks for the answer. I had a look at the available C libraries and unfortunately they only do import or export of FMU but not actually running a simulation (Co-simulation) like your library.

It seems the only way is to actually write a new library similar to FMI4cpp ):
Please feel free to close this issue.

**Comment by markaren** [comment]
Uh, FMI Library does the same thing FMI4cpp does. I did provide a simple CLI for FMI4cpp earlier, but I removed that a long time ago.

**Comment by andre2007** [comment]
Thanks a lot. I think I misunderstood the functionality of the C library.

**Comment by markaren** [comment]
@andre2007 Just FYI, we now have https://github.com/open-simulation-platform/libcosimc, which is a C wrapper for _libcosim_ that does a bit more than just importing FMUs.

**Comment by andre2007** [comment]
Thanks. That looks very promising.
