### ISSUE TITLE
Solve compile errors cause by typed_scalar_variable.hpp

### ISSUE THREAD

**Issue by michi002** [NTNU-IHB/FMI4cpp#99]
When compiling with Visual Studio 2019 errors occur in typed_scalar_variable.hpp since the min and max member functions of bounded_scalar_variable.
This can be solved by undefining the old min and max macros via:

#ifdef max
#undef max
#endif

#ifdef min
#undef min
#endif

**Comment by markaren** [comment]
Care to make a PR? I assume that when this is applied directly to the header, we don't need this definition here anymore: https://github.com/NTNU-IHB/FMI4cpp/blob/d51b3ecc9521a52f3502b691f3de0dc8bf8ad43e/CMakeLists.txt#L30

In another project I was involved with, a similar issue was resolved by applying in the cpp file:

```cpp
#if defined(_WIN32) && !defined(NOMINMAX)
#    define NOMINMAX
#endif
```

However, I'm not sure adding this to the header is a good idea. What if the client project relies on these macros?
Would it be better to just apply it in your own project?

**Comment by markaren** [comment]
Closing due to lack of feedback from issue reporter
